# The rest of the information displayed on the dashboard in each section.

Teacher.create(first_name: "Setsuna", last_name: "Meioh", age: 24, date_of_birth: "October 29, 1978", salary: "75980", education: "Keio University - Ph.D", subject: "Physics")
Teacher.create(first_name: "Wataru", last_name: "Amanogawa", age: 35, date_of_birth: "April 12, 1966", salary: "85980", education: "Kyoto University - Ph.D", subject: "Astronomy")
Teacher.create(first_name: "Haruna", last_name: "Sakurada", age: 25, date_of_birth: "June 24, 1977", salary: "65456", education: "Osaka University - M.S.Ed", subject: "History")
Teacher.create(first_name: "Souichi", last_name: "Tomoe", age: 40, date_of_birth: "December 26, 1964", salary: "85988", education: "Waseda University - Ph.D", subject: "Chemistry")
Teacher.create(first_name: "Mamoru", last_name: "Chiba", age: 23, date_of_birth: "August 3, 1978", salary: "65382", education: "Harvard University - Ph.D", subject: "English")
Teacher.create(first_name: "Yumemi", last_name: "Yumeno", age: 22, date_of_birth: "February 28, 1979", salary: "55294", education: "Tokyo University of the Arts - M.S.Ed", subject: "Studio Art")
Teacher.create(first_name: "Shun", last_name: "Hayase", age: 27, date_of_birth: "January 8, 1973", salary: "55392", education: "Meiji University - M.S.Ed", subject: "Physical Education")
Teacher.create(first_name: "Takuzou", last_name: "Igarashi", age: 30, date_of_birth: "August 24, 1974", salary: "55392", education: "Tokyo University of the Arts - M.S.Ed", subject: "Music")
Teacher.create(first_name: "Ryo", last_name: "Urawa", age: 20, date_of_birth: "January 9, 1978", salary: "75980", education: "Keisen University - M.S.Ed", subject: "Mathematics")
Teacher.create(first_name: "Ikuko", last_name: "Tsukino", age: 40, date_of_birth: "September 28, 1964", salary: "54293", education: "Osaka University - M.S.Ed", subject: "Home Economics")

Course.create(name: "Physics", location: "Lab 1007", description: "Learning about the general concepts of physics such as motion, matter, energy and force within its interaction.", class_hours: "7AM - 8AM")
Course.create(name: "Astronomy", location: "Room 427B", description: "Learning about the general concepts of astronomy such as celestial objects and phenomena within its divine universe.", class_hours: "8AM - 9AM")
Course.create(name: "History", location: "Room 239C", description: "Learning about the most important historical facts that happened in the past stated in such vital documentation.", class_hours: "9AM - 10AM")
Course.create(name: "Chemistry", location: "Lab 1002", description: "Learning about the general concepts of chemistry such as atoms, elements and molecules within its behavioral properties.", class_hours: "10AM - 11AM")
Course.create(name: "English", location: "Room 127D", description: "Learning about the wonderful language and its works of literature and other masterpieces which is English.", class_hours: "11AM - 12PM")
Course.create(name: "Studio Art", location: "Room 538B", description: "Learning about the expression and creative concepts of aesthetics, emotion and beauty through artfacts.", class_hours: "1PM - 2PM")
Course.create(name: "Physical Education", location: "General Gymnasium", description: "Learning about the general concepts of fitness, sportsmanship, athleticism and physical health overall.", class_hours: "2PM - 3PM")
Course.create(name: "Music", location: "Room 530D", description: "Learning about the art form and cultural activity whose medium is sound measured in time.", class_hours: "3PM - 4PM")
Course.create(name: "Mathematics", location: "Room 157A", description: "Learning about the general concepts of mathematics such as computation, quantity, logic and measurement within abstraction in space.", class_hours: "4PM - 5PM")
Course.create(name: "Home Economics", location: "Room 220C", description: "Learning about the general concepts which deals with domestic life with economics in terms of budgeting and financing living expenses.", class_hours: "5PM - 6PM")

Cohort.create(name: "Physics - Volume 1", start_date: "09/05/2018", end_date: "12/19/2018", course_id: 1, teacher_id: 1)
Cohort.create(name: "Astronomy - Volume 1", start_date: "09/05/2018", end_date: "12/19/2018", course_id: 2, teacher_id: 2)
Cohort.create(name: "History - Volume 1", start_date: "09/05/2018", end_date: "12/19/2018", course_id: 3, teacher_id: 3)
Cohort.create(name: "Chemistry - Volume 1", start_date: "09/05/2018", end_date: "12/19/2018", course_id: 4, teacher_id: 4)
Cohort.create(name: "English - Volume 1", start_date: "09/05/2018", end_date: "12/19/2018", course_id: 5, teacher_id: 5)
Cohort.create(name: "Studio Art - Volume 1", start_date: "09/05/2018", end_date: "12/19/2018", course_id: 6, teacher_id: 6)
Cohort.create(name: "Physical Education - Volume 1", start_date: "09/05/2018", end_date: "12/19/2018", course_id: 7, teacher_id: 7)
Cohort.create(name: "Music - Volume 1", start_date: "09/05/2018", end_date: "12/19/2018", course_id: 8, teacher_id: 8)
Cohort.create(name: "Mathematics - Volume 1", start_date: "09/05/2018", end_date: "12/19/2018", course_id: 9, teacher_id: 9)
Cohort.create(name: "Home Economics - Volume 1", start_date: "09/05/2018", end_date: "12/19/2018", course_id: 10, teacher_id: 10)

Student.create(first_name: "Usagi", last_name: "Tsukino", age: 14, date_of_birth: "June 30, 1978", year: "Freshman", cohort_id: 1)
Student.create(first_name: "Ami", last_name: "Mizuno", age: 14, date_of_birth: "September 10, 1978", year: "Freshman", cohort_id: 1)
Student.create(first_name: "Makoto", last_name: "Kino", age: 14, date_of_birth: "December 5, 1978", year: "Freshman", cohort_id: 1)
Student.create(first_name: "Minako", last_name: "Aino", age: 14, date_of_birth: "October 22, 1978", year: "Freshman", cohort_id: 1)
Student.create(first_name: "Haruka", last_name: "Tenoh", age: 15, date_of_birth: "January 27, 1978", year: "Sophomore", cohort_id: 1)
Student.create(first_name: "Michiru", last_name: "Kaioh", age: 15, date_of_birth: "March 6, 1978", year: "Sophomore", cohort_id: 1)
Student.create(first_name: "Seiya", last_name: "Kou", age: 16, date_of_birth: "July 30, 1976", year: "Junior", cohort_id: 1)
Student.create(first_name: "Taiki", last_name: "Kou", age: 16, date_of_birth: "May 30, 1976", year: "Junior", cohort_id: 1)
Student.create(first_name: "Yaten", last_name: "Kou", age: 16, date_of_birth: "February 8, 1976", year: "Junior", cohort_id: 1)
Student.create(first_name: "Naru", last_name: "Osaka", age: 14, date_of_birth: "May 6, 1978", year: "Freshman", cohort_id: 1)
Student.create(first_name: "Gurio", last_name: "Umino", age: 14, date_of_birth: "June 15, 1978", year: "Freshman", cohort_id: 1)
Student.create(first_name: "Sonoko", last_name: "Ijuuin", age: 17, date_of_birth: "November 10, 1975", year: "Senior", cohort_id: 1)
Student.create(first_name: "Yuji", last_name: "Kayama", age: 17, date_of_birth: "December 8, 1975", year: "Senior", cohort_id: 1)
Student.create(first_name: "Nyanko", last_name: "Suzu", age: 15, date_of_birth: "July 5, 1978", year: "Sophomore", cohort_id: 1)
